# Generated by Django 5.2.6 on 2025-09-04 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_entidad_options_alter_gestion_options_and_more'),
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objetivoespecifico',
            options={'ordering': ['codigo'], 'verbose_name': 'Objetivo Específico', 'verbose_name_plural': 'Objetivos Específicos'},
        ),
        migrations.AlterModelOptions(
            name='programa',
            options={'ordering': ['codigo'], 'verbose_name': 'Programa Institucional', 'verbose_name_plural': 'Programas Institucionales'},
        ),
        migrations.AddField(
            model_name='programa',
            name='gestion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.gestion'),
        ),
        migrations.AlterField(
            model_name='objetivoespecifico',
            name='codigo',
            field=models.CharField(help_text='Código jerárquico (ej: 100-0-1)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='objetivoespecifico',
            name='descripcion',
            field=models.TextField(help_text='Descripción del objetivo específico'),
        ),
        migrations.AlterField(
            model_name='objetivoespecifico',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_especificos', to='programas.programa'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='codigo',
            field=models.CharField(help_text='Código del programa (ej: 100, 510, 610)', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='programa',
            name='nombre',
            field=models.CharField(help_text='Nombre del programa (ej: Gestión de la Formación de Pregrado)', max_length=200),
        ),
        migrations.AlterField(
            model_name='programa',
            name='objetivo_institucional',
            field=models.TextField(help_text='Objetivo estratégico de gestión institucional'),
        ),
    ]
