# Generated by Django 5.2.6 on 2025-09-04 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_entidad_options_alter_gestion_options_and_more"),
        ("programas", "0002_alter_objetivoespecifico_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programa",
            name="gestion",
            field=models.ForeignKey(
                help_text="Gestión a la que pertenece el programa",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.gestion",
            ),
        ),
    ]
