# Generated by Django 5.2.6 on 2025-09-03 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('producto_esperado', models.TextField()),
                ('mes_inicio', models.CharField(max_length=20)),
                ('mes_fin', models.CharField(max_length=20)),
                ('monto_asignado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En Curso'), ('realizado', 'Realizado'), ('suspendido', 'Suspendido')], default='pendiente', max_length=20)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gestion')),
                ('objetivo_especifico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programas.objetivoespecifico')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.responsable')),
                ('unidad_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidadsolicitante')),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('linea_base', models.CharField(max_length=50)),
                ('meta', models.CharField(max_length=50)),
                ('medio_verificacion', models.TextField(blank=True, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='actividades.actividad')),
            ],
        ),
    ]
