# Generated by Django 5.2.6 on 2025-09-04 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
        ('core', '0002_alter_entidad_options_alter_gestion_options_and_more'),
        ('programas', '0002_alter_objetivoespecifico_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ['codigo'], 'verbose_name': 'Actividad del POA', 'verbose_name_plural': 'Actividades del POA'},
        ),
        migrations.AlterModelOptions(
            name='indicador',
            options={'verbose_name': 'Indicador', 'verbose_name_plural': 'Indicadores'},
        ),
        migrations.AlterField(
            model_name='actividad',
            name='codigo',
            field=models.CharField(help_text='Código de la actividad (ej: A001)', max_length=20),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En Curso'), ('realizado', 'Realizado'), ('suspendido', 'Suspendido')], default='pendiente', help_text='Estado de avance de la actividad', max_length=20),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Última fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='gestion',
            field=models.ForeignKey(help_text='Año de gestión (ej: 2026)', on_delete=django.db.models.deletion.CASCADE, to='core.gestion'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='mes_fin',
            field=models.CharField(help_text='Mes de finalización (ej: Junio)', max_length=20),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='mes_inicio',
            field=models.CharField(help_text='Mes de inicio (ej: Enero)', max_length=20),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='monto_asignado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto total asignado en Bs.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='nombre',
            field=models.CharField(help_text='Nombre de la actividad', max_length=200),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='objetivo_especifico',
            field=models.ForeignKey(help_text='Objetivo Específico al que pertenece esta actividad', on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='programas.objetivoespecifico'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='producto_esperado',
            field=models.TextField(help_text='Bien, servicio o norma esperado como resultado'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='responsable',
            field=models.ForeignKey(help_text='Responsable de la ejecución', on_delete=django.db.models.deletion.PROTECT, to='core.responsable'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='unidad_solicitante',
            field=models.ForeignKey(help_text='Unidad que elabora y ejecuta la actividad', on_delete=django.db.models.deletion.CASCADE, to='core.unidadsolicitante'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='descripcion',
            field=models.CharField(help_text='Descripción del indicador (ej: N° de estudiantes capacitados)', max_length=200),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='linea_base',
            field=models.CharField(help_text='Valor inicial antes de la actividad', max_length=50),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='medio_verificacion',
            field=models.TextField(blank=True, help_text='Documento o evidencia que verifica el cumplimiento (informe, acta, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='meta',
            field=models.CharField(help_text='Valor esperado al finalizar', max_length=50),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='unidad_medida',
            field=models.CharField(help_text='Unidad (ej: Número, Porcentaje, Horas)', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='actividad',
            unique_together={('codigo', 'gestion')},
        ),
    ]
