# Generated by Django 5.2.6 on 2025-09-04 00:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entidad',
            options={'verbose_name': 'Entidad', 'verbose_name_plural': 'Entidades'},
        ),
        migrations.AlterModelOptions(
            name='gestion',
            options={'ordering': ['-año'], 'verbose_name': 'Gestión', 'verbose_name_plural': 'Gestiones'},
        ),
        migrations.AlterModelOptions(
            name='partidapresupuestaria',
            options={'ordering': ['codigo'], 'verbose_name': 'Partida Presupuestaria', 'verbose_name_plural': 'Partidas Presupuestarias'},
        ),
        migrations.AlterModelOptions(
            name='responsable',
            options={'ordering': ['nombre'], 'verbose_name': 'Responsable', 'verbose_name_plural': 'Responsables'},
        ),
        migrations.AlterModelOptions(
            name='tipounidad',
            options={'verbose_name': 'Tipo de Unidad', 'verbose_name_plural': 'Tipos de Unidad'},
        ),
        migrations.AlterModelOptions(
            name='unidadsolicitante',
            options={'ordering': ['tipo__nombre', 'nombre'], 'verbose_name': 'Unidad Solicitante', 'verbose_name_plural': 'Unidades Solicitantes'},
        ),
        migrations.AddField(
            model_name='unidadsolicitante',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_responsables', to='core.responsable'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='año',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2020)]),
        ),
        migrations.AlterField(
            model_name='tipounidad',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='unidadsolicitante',
            name='codigo_interno',
            field=models.CharField(blank=True, help_text='Código interno (opcional)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unidadsolicitante',
            name='nombre',
            field=models.CharField(help_text='Nombre oficial de la unidad (ej: Carrera de Ingeniería de Sistemas)', max_length=200),
        ),
    ]
