# Generated by Django 5.2.6 on 2025-09-04 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_entidad_options_alter_gestion_options_and_more'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuario'},
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='cargo',
            field=models.CharField(blank=True, help_text='Cargo del usuario (Director, Coordinador, etc.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='unidad',
            field=models.ForeignKey(blank=True, help_text='Unidad académica o administrativa a la que pertenece', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unidadsolicitante'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='user',
            field=models.OneToOneField(help_text='Usuario de Django asociado a este perfil', on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
