# Generated by Django 5.2.6 on 2025-09-03 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=3)),
                ('meta', models.CharField(max_length=50)),
                ('ejecutado', models.CharField(blank=True, max_length=50)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='actividades.indicador')),
            ],
            options={
                'unique_together': {('indicador', 'trimestre')},
            },
        ),
    ]
