# Generated by Django 5.2.6 on 2025-09-04 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_alter_actividad_options_alter_indicador_options_and_more'),
        ('seguimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seguimientoindicador',
            options={'ordering': ['indicador', 'trimestre'], 'verbose_name': 'Seguimiento de Indicador', 'verbose_name_plural': 'Seguimientos de Indicadores'},
        ),
        migrations.RemoveField(
            model_name='seguimientoindicador',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='seguimientoindicador',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='seguimientoindicador',
            name='medio_verificacion',
            field=models.TextField(blank=True, help_text='Documento o evidencia que verifica el cumplimiento (informe, acta, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='seguimientoindicador',
            name='meta_programada',
            field=models.CharField(default='0', help_text='Meta programada para este trimestre', max_length=50),
        ),
        migrations.AlterField(
            model_name='seguimientoindicador',
            name='ejecutado',
            field=models.CharField(blank=True, help_text='Avance físico registrado (puede ser número, porcentaje, etc.)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='seguimientoindicador',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, help_text='Fecha en que se registró el avance'),
        ),
        migrations.AlterField(
            model_name='seguimientoindicador',
            name='indicador',
            field=models.ForeignKey(help_text='Indicador al que se refiere este seguimiento', on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='actividades.indicador'),
        ),
        migrations.AlterField(
            model_name='seguimientoindicador',
            name='trimestre',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], help_text='Trimestre de seguimiento', max_length=3),
        ),
    ]
