# Generated by Django 5.2.6 on 2025-09-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seguimiento", "0002_alter_seguimientoindicador_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seguimientoindicador",
            name="meta_programada",
            field=models.CharField(
                help_text="Meta programada para este trimestre", max_length=50
            ),
        ),
    ]
