# Generated by Django 5.2.6 on 2025-09-03 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('material', 'Material'), ('servicio', 'Servicio'), ('equipo', 'Equipo'), ('insumo', 'Insumo'), ('otro', 'Otro')], max_length=20)),
                ('codigo_interno', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('descripcion', models.TextField()),
                ('unidad_medida_sugerida', models.CharField(blank=True, max_length=50)),
                ('partida_presupuestaria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.partidapresupuestaria')),
            ],
        ),
        migrations.CreateModel(
            name='RecursoSolicitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mes_requerimiento', models.CharField(max_length=50)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.actividad')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.catalogorecurso')),
            ],
        ),
    ]
