# Generated by Django 5.2.6 on 2025-09-04 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_alter_actividad_options_alter_indicador_options_and_more'),
        ('core', '0002_alter_entidad_options_alter_gestion_options_and_more'),
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogorecurso',
            options={'ordering': ['tipo', 'descripcion'], 'verbose_name': 'Catálogo de Recurso', 'verbose_name_plural': 'Catálogo de Recursos'},
        ),
        migrations.AlterModelOptions(
            name='recursosolicitado',
            options={'ordering': ['actividad__codigo'], 'verbose_name': 'Recurso Solicitado', 'verbose_name_plural': 'Recursos Solicitados'},
        ),
        migrations.RemoveField(
            model_name='recursosolicitado',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='recursosolicitado',
            name='recurso',
        ),
        migrations.AddField(
            model_name='recursosolicitado',
            name='cantidad_requerida',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cantidad necesaria', max_digits=10),
        ),
        migrations.AddField(
            model_name='recursosolicitado',
            name='caracteristicas',
            field=models.TextField(blank=True, help_text='Especificaciones técnicas o adicionales', null=True),
        ),
        migrations.AddField(
            model_name='recursosolicitado',
            name='detalle',
            field=models.CharField(default='Por definir', help_text='Descripción del recurso (puede ser del catálogo o personalizado)', max_length=200),
        ),
        migrations.AddField(
            model_name='recursosolicitado',
            name='partida_presupuestaria',
            field=models.ForeignKey(default=1, help_text='Partida presupuestaria (ej: 39500 - Útiles de Oficina)', on_delete=django.db.models.deletion.PROTECT, to='core.partidapresupuestaria'),
        ),
        migrations.AddField(
            model_name='recursosolicitado',
            name='unidad_medida',
            field=models.CharField(default='Unidad', help_text='Unidad de medida (ej: Unidad, Caja, Litro)', max_length=50),
        ),
        migrations.AlterField(
            model_name='catalogorecurso',
            name='codigo_interno',
            field=models.CharField(blank=True, help_text='Código interno del ítem (NRO del Excel)', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='catalogorecurso',
            name='descripcion',
            field=models.TextField(help_text='Descripción detallada del recurso'),
        ),
        migrations.AlterField(
            model_name='catalogorecurso',
            name='partida_presupuestaria',
            field=models.ForeignKey(blank=True, help_text='Partida presupuestaria asociada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.partidapresupuestaria'),
        ),
        migrations.AlterField(
            model_name='catalogorecurso',
            name='tipo',
            field=models.CharField(choices=[('material', 'Material'), ('servicio', 'Servicio'), ('equipo', 'Equipo'), ('insumo', 'Insumo'), ('otro', 'Otro')], help_text='Tipo de recurso', max_length=20),
        ),
        migrations.AlterField(
            model_name='catalogorecurso',
            name='unidad_medida_sugerida',
            field=models.CharField(blank=True, help_text='Unidad de medida sugerida (ej: Unidad, Litro, Galón)', max_length=50),
        ),
        migrations.AlterField(
            model_name='recursosolicitado',
            name='actividad',
            field=models.ForeignKey(help_text='Actividad del POA a la que pertenece este recurso', on_delete=django.db.models.deletion.CASCADE, related_name='recursos_solicitados', to='actividades.actividad'),
        ),
        migrations.AlterField(
            model_name='recursosolicitado',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Calculado automáticamente: cantidad × costo unitario', max_digits=14),
        ),
        migrations.AlterField(
            model_name='recursosolicitado',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, help_text='Precio unitario en Bolivianos (Bs.)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='recursosolicitado',
            name='mes_requerimiento',
            field=models.CharField(help_text='Período de requerimiento (ej: Enero-Junio)', max_length=50),
        ),
    ]
