# Generated by Django 5.2.6 on 2025-09-04 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_entidad_options_alter_gestion_options_and_more"),
        ("recursos", "0002_alter_catalogorecurso_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recursosolicitado",
            name="cantidad_requerida",
            field=models.DecimalField(
                decimal_places=2, help_text="Cantidad necesaria", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="recursosolicitado",
            name="detalle",
            field=models.CharField(
                help_text="Descripción del recurso (puede ser del catálogo o personalizado)",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="recursosolicitado",
            name="partida_presupuestaria",
            field=models.ForeignKey(
                help_text="Partida presupuestaria (ej: 39500 - Útiles de Oficina)",
                on_delete=django.db.models.deletion.PROTECT,
                to="core.partidapresupuestaria",
            ),
        ),
        migrations.AlterField(
            model_name="recursosolicitado",
            name="unidad_medida",
            field=models.CharField(
                help_text="Unidad de medida (ej: Unidad, Caja, Litro)", max_length=50
            ),
        ),
    ]
